### ISSUE TITLE
Monterey Beta 6 Error

### ISSUE THREAD

**Issue by RobSjaras** [ahkohd/switch-desktop#111]
```
TypeError: Object has been destroyed
    at Zt.deliver (/Applications/Switch.app/Contents/Resources/app.asar/main.prod.js:2:49329)
    at Function.refreshAppsList (/Applications/Switch.app/Contents/Resources/app.asar/main.prod.js:2:50805)
    at er.detectAdditonOrRemovalOfApp (/Applications/Switch.app/Contents/Resources/app.asar/main.prod.js:2:50216)
    at FSWatcher.<anonymous> (/Applications/Switch.app/Contents/Resources/app.asar/main.prod.js:2:49804)
    at FSWatcher.emit (events.js:315:20)
    at FSWatcher.emitWithAll (/Applications/Switch.app/Contents/Resources/app.asar/node_modules/chokidar/index.js:534:8)
    at FSWatcher._emit (/Applications/Switch.app/Contents/Resources/app.asar/node_modules/chokidar/index.js:626:8)
    at FsEventsHandler.emitAdd (/Applications/Switch.app/Contents/Resources/app.asar/node_modules/chokidar/lib/fsevents-handler.js:420:14)
    at ReaddirpStream.<anonymous> (/Applications/Switch.app/Contents/Resources/app.asar/node_modules/chokidar/lib/fsevents-handler.js:489:16)
    at ReaddirpStream.emit (events.js:315:20)
```

---

Switch 0.5.2
Electron 11.1.1
darwin 21.1.0
Locale: en-GB

**Comment by ahkohd** [comment]
I'll look into this once i install the update
